# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '^back/.*\.(js)$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.54.0'
    hooks:
      - id: eslint
        files: '^back/.*\.(js)$'
        args: ['--fix']
    